package controls

import "github.com/agentguard/agentguard/internal/models"

// getNIST80053Controls returns NIST SP 800-53 Rev 5 controls most relevant to AI systems.
// This is a subset focusing on controls that map to AI governance requirements.
func getNIST80053Controls() []models.Control {
	return []models.Control{
		// Access Control Family (AC)
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "AC-1",
			Title:            "Policy and Procedures",
			Description:      "Develop, document, and disseminate access control policy and procedures.",
			Objectives:       []string{"Establish access control policy", "Define procedures"},
			Activities:       []string{"Develop policy", "Document procedures", "Communicate to personnel"},
			EvidenceTypes:    []string{"Policy documents", "Procedure documentation"},
			ApplicableLayers: []string{"governance"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "AC-2",
			Title:            "Account Management",
			Description:      "Manage system accounts including creating, enabling, modifying, disabling, and removing accounts.",
			Objectives:       []string{"Manage user accounts", "Control access privileges"},
			Activities:       []string{"Create accounts", "Assign privileges", "Review accounts", "Remove access"},
			EvidenceTypes:    []string{"Account lists", "Access reviews", "Privilege assignments"},
			ApplicableLayers: []string{"system", "operations"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "AC-3",
			Title:            "Access Enforcement",
			Description:      "Enforce approved authorizations for logical access to information and system resources.",
			Objectives:       []string{"Enforce access controls", "Prevent unauthorized access"},
			Activities:       []string{"Implement access controls", "Monitor access", "Enforce policy"},
			EvidenceTypes:    []string{"Access control configurations", "Enforcement logs"},
			ApplicableLayers: []string{"system"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "AC-6",
			Title:            "Least Privilege",
			Description:      "Employ the principle of least privilege, allowing only authorized accesses for users.",
			Objectives:       []string{"Minimize privileges", "Limit access to required functions"},
			Activities:       []string{"Define minimum privileges", "Implement restrictions", "Review privileges"},
			EvidenceTypes:    []string{"Privilege definitions", "Access reviews"},
			ApplicableLayers: []string{"system", "operations"},
		},

		// Audit and Accountability Family (AU)
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "AU-1",
			Title:            "Policy and Procedures",
			Description:      "Develop audit and accountability policy and procedures.",
			Objectives:       []string{"Establish audit policy", "Define audit procedures"},
			Activities:       []string{"Develop policy", "Document procedures"},
			EvidenceTypes:    []string{"Audit policy", "Procedure documentation"},
			ApplicableLayers: []string{"governance"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "AU-2",
			Title:            "Event Logging",
			Description:      "Identify events that require logging to support audit.",
			Objectives:       []string{"Define auditable events", "Enable event logging"},
			Activities:       []string{"Identify events", "Configure logging", "Review logs"},
			EvidenceTypes:    []string{"Event definitions", "Log configurations"},
			ApplicableLayers: []string{"system", "operations"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "AU-3",
			Title:            "Content of Audit Records",
			Description:      "Ensure audit records contain required information.",
			Objectives:       []string{"Define audit record content", "Capture required data"},
			Activities:       []string{"Define content requirements", "Configure record format"},
			EvidenceTypes:    []string{"Record format specifications", "Sample records"},
			ApplicableLayers: []string{"system"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "AU-6",
			Title:            "Audit Record Review, Analysis, and Reporting",
			Description:      "Review and analyze audit records for indications of inappropriate activity.",
			Objectives:       []string{"Review audit records", "Analyze for anomalies"},
			Activities:       []string{"Review logs", "Analyze patterns", "Report findings"},
			EvidenceTypes:    []string{"Review procedures", "Analysis reports"},
			ApplicableLayers: []string{"operations"},
		},

		// Configuration Management Family (CM)
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "CM-1",
			Title:            "Policy and Procedures",
			Description:      "Develop configuration management policy and procedures.",
			Objectives:       []string{"Establish CM policy", "Define CM procedures"},
			Activities:       []string{"Develop policy", "Document procedures"},
			EvidenceTypes:    []string{"CM policy", "Procedure documentation"},
			ApplicableLayers: []string{"governance"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "CM-2",
			Title:            "Baseline Configuration",
			Description:      "Develop, document, and maintain baseline configurations.",
			Objectives:       []string{"Define baselines", "Maintain configurations"},
			Activities:       []string{"Document baseline", "Review configurations", "Update baselines"},
			EvidenceTypes:    []string{"Baseline documentation", "Configuration records"},
			ApplicableLayers: []string{"system"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "CM-3",
			Title:            "Configuration Change Control",
			Description:      "Determine and approve configuration changes with proper analysis.",
			Objectives:       []string{"Control changes", "Approve modifications"},
			Activities:       []string{"Document changes", "Analyze impact", "Approve changes"},
			EvidenceTypes:    []string{"Change requests", "Approval records"},
			ApplicableLayers: []string{"operations"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "CM-4",
			Title:            "Impact Analyses",
			Description:      "Analyze changes for potential security and privacy impacts.",
			Objectives:       []string{"Assess change impacts", "Identify risks"},
			Activities:       []string{"Conduct impact analysis", "Document findings"},
			EvidenceTypes:    []string{"Impact assessments", "Risk documentation"},
			ApplicableLayers: []string{"operations", "risk_management"},
		},

		// Contingency Planning Family (CP)
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "CP-1",
			Title:            "Policy and Procedures",
			Description:      "Develop contingency planning policy and procedures.",
			Objectives:       []string{"Establish CP policy", "Define procedures"},
			Activities:       []string{"Develop policy", "Document procedures"},
			EvidenceTypes:    []string{"CP policy", "Procedure documentation"},
			ApplicableLayers: []string{"governance"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "CP-2",
			Title:            "Contingency Plan",
			Description:      "Develop a contingency plan that addresses recovery objectives.",
			Objectives:       []string{"Plan for contingencies", "Define recovery procedures"},
			Activities:       []string{"Develop plan", "Define recovery steps", "Test plan"},
			EvidenceTypes:    []string{"Contingency plan", "Test results"},
			ApplicableLayers: []string{"operations"},
		},

		// Identification and Authentication Family (IA)
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "IA-1",
			Title:            "Policy and Procedures",
			Description:      "Develop identification and authentication policy and procedures.",
			Objectives:       []string{"Establish IA policy", "Define procedures"},
			Activities:       []string{"Develop policy", "Document procedures"},
			EvidenceTypes:    []string{"IA policy", "Procedure documentation"},
			ApplicableLayers: []string{"governance"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "IA-2",
			Title:            "Identification and Authentication (Organizational Users)",
			Description:      "Uniquely identify and authenticate organizational users.",
			Objectives:       []string{"Identify users", "Authenticate access"},
			Activities:       []string{"Implement user identification", "Configure authentication"},
			EvidenceTypes:    []string{"Authentication configurations", "User records"},
			ApplicableLayers: []string{"system"},
		},

		// Planning Family (PL)
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "PL-1",
			Title:            "Policy and Procedures",
			Description:      "Develop security and privacy planning policy and procedures.",
			Objectives:       []string{"Establish planning policy", "Define procedures"},
			Activities:       []string{"Develop policy", "Document procedures"},
			EvidenceTypes:    []string{"Planning policy", "Procedure documentation"},
			ApplicableLayers: []string{"governance"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "PL-2",
			Title:            "System Security and Privacy Plans",
			Description:      "Develop security and privacy plans consistent with architecture.",
			Objectives:       []string{"Document security plans", "Plan privacy controls"},
			Activities:       []string{"Develop plans", "Review and update"},
			EvidenceTypes:    []string{"Security plans", "Privacy documentation"},
			ApplicableLayers: []string{"governance", "system"},
		},

		// Risk Assessment Family (RA)
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "RA-1",
			Title:            "Policy and Procedures",
			Description:      "Develop risk assessment policy and procedures.",
			Objectives:       []string{"Establish RA policy", "Define procedures"},
			Activities:       []string{"Develop policy", "Document procedures"},
			EvidenceTypes:    []string{"RA policy", "Procedure documentation"},
			ApplicableLayers: []string{"governance"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "RA-3",
			Title:            "Risk Assessment",
			Description:      "Conduct risk assessments to identify and prioritize risks.",
			Objectives:       []string{"Identify risks", "Assess risk levels"},
			Activities:       []string{"Conduct assessment", "Document risks", "Prioritize"},
			EvidenceTypes:    []string{"Risk assessment reports", "Risk register"},
			ApplicableLayers: []string{"risk_management"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "RA-5",
			Title:            "Vulnerability Monitoring and Scanning",
			Description:      "Monitor and scan for vulnerabilities in the system.",
			Objectives:       []string{"Identify vulnerabilities", "Monitor security posture"},
			Activities:       []string{"Conduct scans", "Analyze results", "Remediate findings"},
			EvidenceTypes:    []string{"Scan reports", "Remediation records"},
			ApplicableLayers: []string{"system", "operations"},
		},

		// System and Communications Protection Family (SC)
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "SC-1",
			Title:            "Policy and Procedures",
			Description:      "Develop system and communications protection policy and procedures.",
			Objectives:       []string{"Establish SC policy", "Define procedures"},
			Activities:       []string{"Develop policy", "Document procedures"},
			EvidenceTypes:    []string{"SC policy", "Procedure documentation"},
			ApplicableLayers: []string{"governance"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "SC-7",
			Title:            "Boundary Protection",
			Description:      "Monitor and control communications at external and internal boundaries.",
			Objectives:       []string{"Protect boundaries", "Control communications"},
			Activities:       []string{"Implement boundary controls", "Monitor traffic"},
			EvidenceTypes:    []string{"Boundary configurations", "Traffic logs"},
			ApplicableLayers: []string{"system"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "SC-8",
			Title:            "Transmission Confidentiality and Integrity",
			Description:      "Protect confidentiality and integrity of transmitted information.",
			Objectives:       []string{"Protect data in transit", "Ensure integrity"},
			Activities:       []string{"Implement encryption", "Verify integrity"},
			EvidenceTypes:    []string{"Encryption configurations", "Integrity verification"},
			ApplicableLayers: []string{"system"},
		},

		// System and Information Integrity Family (SI)
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "SI-1",
			Title:            "Policy and Procedures",
			Description:      "Develop system and information integrity policy and procedures.",
			Objectives:       []string{"Establish SI policy", "Define procedures"},
			Activities:       []string{"Develop policy", "Document procedures"},
			EvidenceTypes:    []string{"SI policy", "Procedure documentation"},
			ApplicableLayers: []string{"governance"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "SI-4",
			Title:            "System Monitoring",
			Description:      "Monitor the system to detect attacks and unauthorized activities.",
			Objectives:       []string{"Detect attacks", "Monitor activities"},
			Activities:       []string{"Implement monitoring", "Analyze events", "Respond to alerts"},
			EvidenceTypes:    []string{"Monitoring configurations", "Alert logs"},
			ApplicableLayers: []string{"system", "operations"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "SI-5",
			Title:            "Security Alerts, Advisories, and Directives",
			Description:      "Receive security alerts and take appropriate actions.",
			Objectives:       []string{"Stay informed of threats", "Respond to advisories"},
			Activities:       []string{"Subscribe to alerts", "Assess applicability", "Implement responses"},
			EvidenceTypes:    []string{"Alert subscriptions", "Response records"},
			ApplicableLayers: []string{"operations"},
		},
		{
			FrameworkID:      string(FrameworkNIST80053),
			ControlID:        "SI-12",
			Title:            "Information Management and Retention",
			Description:      "Manage and retain information within the system.",
			Objectives:       []string{"Manage information lifecycle", "Retain required data"},
			Activities:       []string{"Define retention policies", "Implement retention", "Dispose properly"},
			EvidenceTypes:    []string{"Retention policies", "Disposal records"},
			ApplicableLayers: []string{"data", "governance"},
		},
	}
}
